---
- name: Update Tenant
  hosts: bigip
  gather_facts: false
  connection: local
    
  vars:
    tenant_body: "{{ lookup('file', '../app-templates/{{ f5_template }}.json', split_lines=False) }}"
    uri_method: "POST"
    vip_ip: "{{ vip_ip }}"

  tasks:

    ##### AS3 POST ##### 
  - name: URI POST Tenant
    uri:
       url: "https://{{ inventory_hostname }}/mgmt/shared/appsvcs/declare"
       method: "{{ uri_method }}"
       user: "admin"
       password: "W3lcome098!"
       validate_certs: no
       vip_ip: "{{ vip_ip }}"
       body: "{{ lookup('template', '../j2/tenant_base.j2') }}"
       body_format: json
